### ISSUE TITLE
Error executing main.py

### ISSUE THREAD

**Issue by salacpavel** [microsoft/routeros-scanner#21]
Traceback (most recent call last):
  File "C:\apps\routeros-scanner-main\main.py", line 62, in <module>
    main(args)
  File "C:\apps\routeros-scanner-main\main.py", line 31, in main
    res = command.run_ssh(ssh_client)
  File "C:\apps\routeros-scanner-main\commands\dns.py", line 16, in run_ssh
    sus_dns, recommendation = self.check_results_ssh(res, enabled)
  File "C:\apps\routeros-scanner-main\commands\dns.py", line 27, in check_results_ssh
    if int(item['ttl'].partition('s')[0]) > 200000:
ValueError: invalid literal for int() with base 10: '2h11m36'

**Comment by vjirovsky** [comment]
same here:
```
...(truncated)...
    if int(item['ttl'].partition('s')[0]) > 200000:
ValueError: invalid literal for int() with base 10: '1d'
```

**Comment by vjirovsky** [comment]
@salacpavel  see workaround in #14

**Comment by salacpavel** [comment]
That did it, thank you.

**Comment by noafru** [comment]
Hi, we uploaded several in-house fixes, one of them for this issue. You can see the updates here: https://github.com/microsoft/routeros-scanner/pull/24
